name: Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck datamash bc
    
    - name: Run shellcheck
      run: |
        echo "Running shellcheck on all bash scripts..."
        find . -name "*.sh" -type f -exec shellcheck {} + || true
    
    - name: Make test scripts executable
      run: chmod +x tests/*.sh src/*.sh
    
    - name: Run all tests
      run: |
        cd tests
        bash run_all_tests.sh
    
    - name: Test data_pipeline.sh
      run: bash tests/test_data_pipeline.sh
      
    - name: Test log_analyzer.sh
      run: bash tests/test_log_analyzer.sh
